// hash: #be879c5e
// @formatter:off

package wietbot.data.messages.models.builders

import wietbot.data.messages.models.models.*
import wietbot.data.messages.models.models.DefaultChatUser

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class ChatUserBuilder
{
	var localId: String? = null
	
	var localName: String? = null
	
	var platform: Platform? = null
	
	var internalId: Long? = null
	
	var stackOverflowId: String? = null
	
	var stackOverflowName: String? = null
	
	var discordId: String? = null
	
	var discordName: String? = null
	
	var wietbotWebsiteId: String? = null
	
	var wietbotWebsiteName: String? = null
	
	fun build(): ChatUser =
		DefaultChatUser(
			localId!!,
			localName!!,
			platform!!,
			internalId!!,
			stackOverflowId,
			stackOverflowName,
			discordId,
			discordName,
			wietbotWebsiteId,
			wietbotWebsiteName,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
