// hash: #a29096b2
// @formatter:off

package wietbot.data.messages.models.builders

import wietbot.data.messages.models.models.*
import wietbot.data.messages.models.models.DefaultMessageSource

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class MessageSourceBuilder
{
	var id: String? = null
	
	var name: String? = null
	
	var platform: Platform? = null
	
	fun build(): MessageSource =
		DefaultMessageSource(
			id!!,
			name!!,
			platform!!,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
