// hash: #5f2831ba
// @formatter:off

package wietbot.data.messages.models.builders

import wietbot.data.messages.models.models.*
import wietbot.data.messages.models.models.DefaultTagPart

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class TagPartBuilder
{
	var name: String? = null
	
	fun build(): TagPart =
		DefaultTagPart(
			name!!,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
