// hash: #97060438
// @formatter:off

package wietbot.data.messages.models.builders

import wietbot.data.messages.models.models.*
import wietbot.data.messages.models.models.DefaultUrlPart

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:f5k3GB
// @tomplot:customCode:end
// @formatter:off

class UrlPartBuilder
{
	var href: String? = null
	
	var text: ContentPart? = null
	
	var title: ContentPart? = null
	
	fun build(): UrlPart =
		DefaultUrlPart(
			href!!,
			text!!,
			title,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:0ETUWm
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
