// hash: #dfe1528d
// @formatter:off

package wietbot.data.messages.models.builders

// Generated by BitBlock version 1.0.0

object WietbotDataMessagesBuilderFacade
{
	fun buildMessageEventList(body: MessageEventListBuilder.() -> Unit) =
		MessageEventListBuilder()
			.apply(body)
			.build()
	
	fun buildMessagePostedEvent(body: MessagePostedEventBuilder.() -> Unit) =
		MessagePostedEventBuilder()
			.apply(body)
			.build()
	
	fun buildMessageEditedEvent(body: MessageEditedEventBuilder.() -> Unit) =
		MessageEditedEventBuilder()
			.apply(body)
			.build()
	
	fun buildMessageDeletedEvent(body: MessageDeletedEventBuilder.() -> Unit) =
		MessageDeletedEventBuilder()
			.apply(body)
			.build()
	
	fun buildChatUser(body: ChatUserBuilder.() -> Unit) =
		ChatUserBuilder()
			.apply(body)
			.build()
	
	fun buildMessageSource(body: MessageSourceBuilder.() -> Unit) =
		MessageSourceBuilder()
			.apply(body)
			.build()
	
	fun buildContent(body: ContentBuilder.() -> Unit) =
		ContentBuilder()
			.apply(body)
			.build()
	
	fun buildMultiPart(body: MultiPartBuilder.() -> Unit) =
		MultiPartBuilder()
			.apply(body)
			.build()
	
	fun buildTextPart(body: TextPartBuilder.() -> Unit) =
		TextPartBuilder()
			.apply(body)
			.build()
	
	fun buildMonospacedPart(body: MonospacedPartBuilder.() -> Unit) =
		MonospacedPartBuilder()
			.apply(body)
			.build()
	
	fun buildInlineMonospacedPart(body: InlineMonospacedPartBuilder.() -> Unit) =
		InlineMonospacedPartBuilder()
			.apply(body)
			.build()
	
	fun buildUrlPart(body: UrlPartBuilder.() -> Unit) =
		UrlPartBuilder()
			.apply(body)
			.build()
	
	fun buildQuotePart(body: QuotePartBuilder.() -> Unit) =
		QuotePartBuilder()
			.apply(body)
			.build()
	
	fun buildBoldPart(body: BoldPartBuilder.() -> Unit) =
		BoldPartBuilder()
			.apply(body)
			.build()
	
	fun buildItalicPart(body: ItalicPartBuilder.() -> Unit) =
		ItalicPartBuilder()
			.apply(body)
			.build()
	
	fun buildStrikeoutPart(body: StrikeoutPartBuilder.() -> Unit) =
		StrikeoutPartBuilder()
			.apply(body)
			.build()
	
	fun buildTagPart(body: TagPartBuilder.() -> Unit) =
		TagPartBuilder()
			.apply(body)
			.build()
	
	fun buildPlatform(body: PlatformBuilder.() -> Unit) =
		PlatformBuilder()
			.apply(body)
			.build()
}
// @formatter:on
