// hash: #d300d07f
// data: serializationKey:a9b808b4-f21c-4992-857d-14644bdfe0ad
// @formatter:off

package wietbot.data.messages.models.models

import bitblock.api.serialization.BitSerializable
import java.util.UUID
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface ChatUser : BitSerializable, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("a9b808b4-f21c-4992-857d-14644bdfe0ad")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val localId: String
	
	val localName: String
	
	val platform: Platform
	
	val internalId: Long
	
	val stackOverflowId: String?
	
	val stackOverflowName: String?
	
	val discordId: String?
	
	val discordName: String?
	
	val wietbotWebsiteId: String?
	
	val wietbotWebsiteName: String?
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is ChatUser) return false
		
		if (localId != other.localId) return false
		if (localName != other.localName) return false
		if (platform != other.platform) return false
		if (internalId != other.internalId) return false
		if (stackOverflowId != other.stackOverflowId) return false
		if (stackOverflowName != other.stackOverflowName) return false
		if (discordId != other.discordId) return false
		if (discordName != other.discordName) return false
		if (wietbotWebsiteId != other.wietbotWebsiteId) return false
		if (wietbotWebsiteName != other.wietbotWebsiteName) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(localId)
			.with(localName)
			.with(platform)
			.with(internalId)
			.with(stackOverflowId)
			.with(stackOverflowName)
			.with(discordId)
			.with(discordName)
			.with(wietbotWebsiteId)
			.with(wietbotWebsiteName)
	
	override fun toJson(): String =
		"""{"localId":${localId.toJsonString()},"localName":${localName.toJsonString()},"platform":${platform.toJsonString()},"internalId":${internalId.toJsonString()},"stackOverflowId":${stackOverflowId.toJsonString()},"stackOverflowName":${stackOverflowName.toJsonString()},"discordId":${discordId.toJsonString()},"discordName":${discordName.toJsonString()},"wietbotWebsiteId":${wietbotWebsiteId.toJsonString()},"wietbotWebsiteName":${wietbotWebsiteName.toJsonString()}}"""
	
	override fun duplicate(): ChatUser
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
