// hash: #4392fcfc
// @formatter:off

package wietbot.data.messages.models.models

import bitblock.api.serialization.BitSerializable
import utils.common.Jsonable

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:WTcTph
// @tomplot:customCode:end
// @formatter:off

sealed interface ChatEvent : BitSerializable, Jsonable
{
	val id: String
	
	val timeStamp: Long
	
	val messageId: String
	
	val user: ChatUser
	
	val source: MessageSource
	
	val platform: Platform
	
	override fun duplicate(): ChatEvent
	
	// @formatter:on
	// @tomplot:customCode:start:0MOZ71
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
