// hash: #1bc7885b
// data: serializationKey:e6a51bcb-72f2-4061-8a7c-ddb942021e6a
// @formatter:off

package wietbot.data.messages.models.models

import bitblock.api.serialization.BitSerializable
import java.util.UUID
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface Content : BitSerializable, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("e6a51bcb-72f2-4061-8a7c-ddb942021e6a")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val part: ContentPart
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is Content) return false
		
		if (part != other.part) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(part)
	
	override fun toJson(): String =
		"""{"part":${part.toJsonString()}}"""
	
	override fun duplicate(): Content
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
