// hash: #dfdace70
// @formatter:off

package wietbot.data.messages.models.models

import wietbot.data.messages.models.models.*

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:B8CiSn
// @tomplot:customCode:end
// @formatter:off

data class DefaultPlatform(
	override val name: String,
) : Platform
{
	companion object
	{
		val stackOverflow: DefaultPlatform = DefaultPlatform("stack-overflow")
		
		val discord: DefaultPlatform = DefaultPlatform("discord")
		
		val wietbotWebsite: DefaultPlatform = DefaultPlatform("wietbot-website")
	}
	
	override fun equals(other: Any?): Boolean =
		isEqualTo(other)
	
	override fun hashCode(): Int =
		computeHashCode()
	
	override fun toString(): String =
		toJson()
	
	override fun duplicate(): DefaultPlatform =
		copy(
			name = name,
		)
	
	// @formatter:on
	// @tomplot:customCode:start:fIpaBB
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
