// hash: #faece5d5
// @formatter:off

package wietbot.data.messages.models.models

import bitblock.api.serialization.BitSerializable
import utils.common.Jsonable

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:WTcTph
// @tomplot:customCode:end
// @formatter:off

sealed interface MessageEvent : BitSerializable, ChatEvent, Jsonable
{
	val content: Content
	
	override fun duplicate(): MessageEvent
	
	// @formatter:on
	// @tomplot:customCode:start:0MOZ71
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
