// hash: #baac3610
// data: serializationKey:2059b9b6-4bd7-4205-bdf8-40416431ee86
// @formatter:off

package wietbot.data.messages.models.models

import bitblock.api.serialization.BitSerializable
import java.util.UUID
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface MessageEventList : BitSerializable, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("2059b9b6-4bd7-4205-bdf8-40416431ee86")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val messageId: String
	
	val events: List<ChatEvent>
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is MessageEventList) return false
		
		if (messageId != other.messageId) return false
		if (events != other.events) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(messageId)
			.with(events)
	
	override fun toJson(): String =
		"""{"messageId":${messageId.toJsonString()},"events":${events.toJsonString()}}"""
	
	override fun duplicate(): MessageEventList
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
