// hash: #96c8b255
// data: serializationKey:0dca7f8a-642f-452b-ba90-fddfa1007922
// @formatter:off

package wietbot.data.messages.models.models

import bitblock.api.serialization.BitSerializable
import java.util.UUID
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface MultiPart : BitSerializable, ContentPart, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("0dca7f8a-642f-452b-ba90-fddfa1007922")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val parts: List<ContentPart>
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is MultiPart) return false
		
		if (parts != other.parts) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(parts)
	
	override fun toJson(): String =
		"""{"parts":${parts.toJsonString()}}"""
	
	override fun duplicate(): MultiPart
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
