// hash: #d4078def
// data: serializationKey:81fd7a87-1747-4264-b635-95238caaee8c
// @formatter:off

package wietbot.data.messages.models.models

import bitblock.api.serialization.BitSerializable
import java.util.UUID
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface StrikeoutPart : BitSerializable, ContentPart, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("81fd7a87-1747-4264-b635-95238caaee8c")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val inner: ContentPart
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is StrikeoutPart) return false
		
		if (inner != other.inner) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(inner)
	
	override fun toJson(): String =
		"""{"inner":${inner.toJsonString()}}"""
	
	override fun duplicate(): StrikeoutPart
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
