// hash: #f064463c
// data: serializationKey:e1773d00-1513-4ddf-9bd7-6dd354b7fa90
// @formatter:off

package wietbot.data.messages.models.models

import bitblock.api.serialization.BitSerializable
import java.util.UUID
import utils.common.Jsonable
import utils.common.emptyHashCode
import utils.common.toJsonString
import utils.common.with

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:gAeCSq
// @tomplot:customCode:end
// @formatter:off

interface UrlPart : BitSerializable, ContentPart, Jsonable
{
	companion object
	{
		val serializationKey: UUID
			get() = UUID.fromString("e1773d00-1513-4ddf-9bd7-6dd354b7fa90")
	}
	
	override val serializationKey: UUID
		get() = Companion.serializationKey
	
	val href: String
	
	val text: ContentPart
	
	val title: ContentPart?
	
	fun isEqualTo(other: Any?): Boolean
	{
		if (this === other) return true
		if (other == null) return false
		if (other !is UrlPart) return false
		
		if (href != other.href) return false
		if (text != other.text) return false
		if (title != other.title) return false
		
		return true
	}
	
	fun computeHashCode(): Int =
		emptyHashCode
			.with(href)
			.with(text)
			.with(title)
	
	override fun toJson(): String =
		"""{"href":${href.toJsonString()},"text":${text.toJsonString()},"title":${title.toJsonString()}}"""
	
	override fun duplicate(): UrlPart
	
	// @formatter:on
	// @tomplot:customCode:start:32T3K8
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
