// hash: #03783b4f
// @formatter:off

package wietbot.data.messages.models

import bitblock.api.registry.ModelRegistry
import bitblock.api.registry.ModelRegistryKey
import bitblock.api.registry.RegistrySet
import bitblock.api.serialization.ModelSerializer
import bitblock.core.BitBlockBase
import bitblock.core.registry.CommonModelRegistryKey
import wietbot.data.messages.models.serializers.*

// Generated by BitBlock version 1.0.0

object WietbotDataMessages : RegistrySet
{
	override val modelSerializers: Map<ModelRegistryKey, ModelSerializer<*, *>> = createModelSerializers()
	
	private fun createModelSerializers(): Map<ModelRegistryKey, ModelSerializer<*, *>> =
		mapOf(
			CommonModelRegistryKey("MessageEventList", "WietbotDataMessages", "Wietbot", "1.0") to MessageEventListSerializer,
			CommonModelRegistryKey("MessagePostedEvent", "WietbotDataMessages", "Wietbot", "1.0") to MessagePostedEventSerializer,
			CommonModelRegistryKey("MessageEditedEvent", "WietbotDataMessages", "Wietbot", "1.0") to MessageEditedEventSerializer,
			CommonModelRegistryKey("MessageDeletedEvent", "WietbotDataMessages", "Wietbot", "1.0") to MessageDeletedEventSerializer,
			CommonModelRegistryKey("ChatUser", "WietbotDataMessages", "Wietbot", "1.0") to ChatUserSerializer,
			CommonModelRegistryKey("MessageSource", "WietbotDataMessages", "Wietbot", "1.0") to MessageSourceSerializer,
			CommonModelRegistryKey("Content", "WietbotDataMessages", "Wietbot", "1.0") to ContentSerializer,
			CommonModelRegistryKey("MultiPart", "WietbotDataMessages", "Wietbot", "1.0") to MultiPartSerializer,
			CommonModelRegistryKey("TextPart", "WietbotDataMessages", "Wietbot", "1.0") to TextPartSerializer,
			CommonModelRegistryKey("MonospacedPart", "WietbotDataMessages", "Wietbot", "1.0") to MonospacedPartSerializer,
			CommonModelRegistryKey("InlineMonospacedPart", "WietbotDataMessages", "Wietbot", "1.0") to InlineMonospacedPartSerializer,
			CommonModelRegistryKey("UrlPart", "WietbotDataMessages", "Wietbot", "1.0") to UrlPartSerializer,
			CommonModelRegistryKey("QuotePart", "WietbotDataMessages", "Wietbot", "1.0") to QuotePartSerializer,
			CommonModelRegistryKey("BoldPart", "WietbotDataMessages", "Wietbot", "1.0") to BoldPartSerializer,
			CommonModelRegistryKey("ItalicPart", "WietbotDataMessages", "Wietbot", "1.0") to ItalicPartSerializer,
			CommonModelRegistryKey("StrikeoutPart", "WietbotDataMessages", "Wietbot", "1.0") to StrikeoutPartSerializer,
			CommonModelRegistryKey("TagPart", "WietbotDataMessages", "Wietbot", "1.0") to TagPartSerializer,
			CommonModelRegistryKey("Platform", "WietbotDataMessages", "Wietbot", "1.0") to PlatformSerializer,
		)
	
	override fun initialize(registry: ModelRegistry?) =
		modelSerializers.forEach((registry ?: BitBlockBase.modelRegistry)::set)
}
// @formatter:on
