// hash: #86d42b13
// @formatter:off

package wietbot.data.messages.models.serializers

import bitblock.api.serialization.DeserializationContext
import bitblock.api.serialization.ModelSerializer
import bitblock.api.serialization.Schema
import bitblock.api.serialization.SerializationContext
import bitblock.api.serialization.deserialize
import java.io.InputStream
import java.io.OutputStream
import java.util.UUID
import utils.common.streams.readUnsignedVarInt
import utils.common.streams.writeUnsignedVarInt
import wietbot.data.messages.models.builders.MessageEventListBuilder
import wietbot.data.messages.models.models.*
import wietbot.data.messages.models.models.MessageEventList

// Generated by BitBlock version 1.0.0

// @formatter:on
// @tomplot:customCode:start:70v0f9
// @tomplot:customCode:end
// @formatter:off

object MessageEventListSerializer : ModelSerializer<MessageEventList, MessageEventList>
{
	private val endOfObject: Int = 0
	
	private val messageIdIndex: Int = 1
	
	private val eventsIndex: Int = 2
	
	override val modelId: UUID
		get() = MessageEventList.serializationKey
	
	override val dataClass: Class<MessageEventList>
		get() = MessageEventList::class.java
	
	override fun serialize(serializationContext: SerializationContext, stream: OutputStream, schema: Schema, entity: MessageEventList)
	{
		stream.writeUnsignedVarInt(messageIdIndex)
		schema.serialize(serializationContext, stream, entity.messageId)
		
		stream.writeUnsignedVarInt(eventsIndex)
		schema.serialize(serializationContext, stream, entity.events)
		
		stream.writeUnsignedVarInt(endOfObject)
	}
	
	override fun deserialize(deserializationContext: DeserializationContext, stream: InputStream, schema: Schema): MessageEventList
	{
		var messageId: String? = null
		var events: MutableList<ChatEvent>? = mutableListOf()
		
		while (true)
		{
			when (stream.readUnsignedVarInt())
			{
				endOfObject -> return DefaultMessageEventList(
					messageId!!,
					events!!.toMutableList(),
				)
				messageIdIndex -> messageId = schema.deserialize(deserializationContext, stream)
				eventsIndex -> events = schema.deserialize(deserializationContext, stream)
				else -> schema.deserialize<Any>(deserializationContext, stream)
			}
		}
	}
	
	// @formatter:on
	// @tomplot:customCode:start:5CFs54
	// @tomplot:customCode:end
	// @formatter:off
}
// @formatter:on
